services:

    baikal.rest.controller.calendar:
        class: Baikal\RestBundle\Controller\CalendarController
        arguments:
            - @fos_rest.view_handler
            - @security.context
            - @baikal.repository.calendar

            - @doctrine.orm.entity_manager
            - @baikal.davservice.backend.caldav

    baikal.rest.controller.expandedevent:
        class: Baikal\RestBundle\Controller\ExpandedeventController
        arguments:
            - @fos_rest.view_handler
            - @security.context
            - @baikal.repository.event
            - @baikal.helper.davtimezonehelper

    baikal.rest.controller.event:
        class: Baikal\RestBundle\Controller\EventController
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - @form.factory
            - @fos_rest.view_handler
            - @security.context

            - @baikal.repository.calendar
            - @baikal.repository.event
            
            - @baikal.helper.davtimezonehelper
            - @baikal.davservice.backend.caldav

    baikal.rest.controller.addressbook:
        class: Baikal\RestBundle\Controller\AddressbookController
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - @form.factory
            - @fos_rest.view_handler
            - @security.context

            - @baikal.repository.addressbook

    baikal.rest.controller.contact:
        class: Baikal\RestBundle\Controller\ContactController
        arguments:
            - @fos_rest.view_handler
            - @security.context
            - @baikal.repository.contact

    baikal.rest.serializer.calendar:
        class: Baikal\RestBundle\Serializer\CalendarSerializationSubscriber
        arguments:
            - @baikal.helper.davtimezonehelper
        tags:
            - { name: jms_serializer.event_subscriber }

    baikal.rest.serializer.event:
        class: Baikal\RestBundle\Serializer\EventSerializationSubscriber
        arguments:
            - @baikal.helper.davtimezonehelper
        tags:
            - { name: jms_serializer.event_subscriber }

    baikal.rest.serializer.addressbook:
        class: Baikal\RestBundle\Serializer\AddressbookSerializationSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    baikal.rest.serializer.contact:
        class: Baikal\RestBundle\Serializer\AddressbookContactSerializationSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }